spring.application.name=braincampus-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/braincampus
spring.datasource.username=postgres
spring.datasource.password=Harsh@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=4nA5L8mP2xQ9vK6wR7yT3uI8oP1sD4fG9hJ2kL5zX6cV0bN3mQ8rT1yU4iO7pA2
# 15 Minutes
jwt.access-token-expiration=900000
# 7 Days
jwt.refresh-token-expiration=604800000
