package com.braincampus.common.enums;
public enum PermissionType {

    CREATE_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    VIEW_STUDENT,

    CREATE_TEACHER,
    UPDATE_TEACHER,
    DELETE_TEACHER,
    VIEW_TEACHER,

    CREATE_CLASS,
    UPDATE_CLASS,
    DELETE_CLASS,
    VIEW_CLASS,

    CREATE_SUBJECT,
    UPDATE_SUBJECT,
    DELETE_SUBJECT,
    VIEW_SUBJECT,

    CREATE_STAFF,
    UPDATE_STAFF,
    DELETE_STAFF,
    VIEW_STAFF,

    CREATE_SALARY_STRUCTURE,
    UPDATE_SALARY_STRUCTURE,
    DELETE_SALARY_STRUCTURE,
    VIEW_SALARY_STRUCTURE,

    CREATE_SALARY_PAYMENT,
    UPDATE_SALARY_PAYMENT,
    DELETE_SALARY_PAYMENT,
    VIEW_SALARY_PAYMENT,

    CREATE_EXPENSE,
    UPDATE_EXPENSE,
    DELETE_EXPENSE,
    VIEW_EXPENSE,

    VIEW_FEE_REPORT,
    VIEW_DASHBOARD,
    MANAGE_ROLE_PERMISSIONS
}